version: 2
project_name: subcablemap-dl
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - binary: subcablemap-dl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{.CommitTimestamp}}"
    ignore:
      - goos: windows
        goarch: arm
        goarm: 7
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - src: LICENSE
        info: &info
          owner: 0
          group: 0
          mtime: "{{.CommitDate}}"
          mode: 0644
      - src: README.md
        info: *info
      - src: manpages/*
        info: *info
      - src: completions/*
        info: *info
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Breaking Changes
      order: 0
      regexp: '\)!:'
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Others
      order: 999
brews:
  - homepage: https://github.com/gabe565/subcablemap-dl
    description: Download full-resolution versions of Telegeography Submarine Cable Maps
    license: MIT
    repository:
      owner: gabe565
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "subcablemap-dl"
      man1.install "manpages/subcablemap-dl.1.gz"
      bash_completion.install "completions/subcablemap-dl.bash" => "subcablemap-dl"
      zsh_completion.install "completions/subcablemap-dl.zsh" => "_subcablemap-dl"
      fish_completion.install "completions/subcablemap-dl.fish"
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/subcablemap-dl
    description: Download full-resolution versions of Telegeography Submarine Cable Maps
    license: MIT
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/
        dst: /usr/share/man/man1
        file_info:
          mode: 0644
      - src: ./completions/subcablemap-dl.bash
        dst: /usr/share/bash-completion/completions/subcablemap-dl
        file_info:
          mode: 0644
      - src: ./completions/subcablemap-dl.fish
        dst: /usr/share/fish/vendor_completions.d/subcablemap-dl.fish
        file_info:
          mode: 0644
      - src: ./completions/subcablemap-dl.zsh
        dst:  /usr/share/zsh/vendor-completions/_subcablemap-dl
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
aurs:
  - name: subcablemap-dl-bin
    homepage: https://github.com/gabe565/subcablemap-dl
    description: Download full-resolution versions of Telegeography Submarine Cable Maps
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/subcablemap-dl-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./subcablemap-dl" "${pkgdir}/usr/bin/subcablemap-dl"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/subcablemap-dl/LICENSE"
      # man pages
      install -Dm644 "./manpages/subcablemap-dl.1.gz" "${pkgdir}/usr/share/man/man1/subcablemap-dl.1.gz"
      # completions
      install -Dm644 "./completions/subcablemap-dl.bash" "${pkgdir}/usr/share/bash-completion/completions/subcablemap-dl"
      install -Dm644 "./completions/subcablemap-dl.zsh" "${pkgdir}/usr/share/zsh/site-functions/_subcablemap-dl"
      install -Dm644 "./completions/subcablemap-dl.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/subcablemap-dl.fish"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
dockers:
  - &dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
